config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'sessions/index'

  get 'sessions/import'
  get 'speakers/import'

  get 'programs/:id/download', to: 'programs#download', as: 'program_download'

  get 'programs/:program_id/sessions/:id/download', to: 'sessions#download', as: 'program_session_download'

  get 'programs/:id/text', to: 'programs#text', as: 'program_text'

  #get "/pages/welcome", to: "pages#welcome", as: 'pages_welcome'
  #get "/pages/howto", to: "pages#howto", as: 'pages_howto'

  get "/pages/:page" => "pages#show"
  

  resources :programs do 
    resources :speakers
    resources :sessions
  end

  root to: 'pages#show', page: "welcome"
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :sessions, :dependent => :destroy
  has_many :speakers, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :sessions 
  accepts_nested_attributes_for :speakers


  def delete_if_name_is_nil
    sessions.as_json.delete_if {|session| session["name"] == nil || session["deleted"] == true }
  end

  def delete_if_name_is_nil_speaker
    speakers.as_json.delete_if {|speaker| speaker["speaker_id"] == nil }
  end

  def did_speakers_update(sess_id)
    speak_ids_ary = sessions.find_by(session_id: sess_id).speaker_id.split(",")
    return false if ( speak_ids_ary == nil || speak_ids_ary.include?(nil) )
    speak_updated_at = speak_ids_ary.map { |speakerid| Speaker.find_by(speaker_id: speakerid, program_id: id).updated_at.strftime('%c') }
    if (import_time != nil) && (speak_updated_at.include? import_time.strftime('%c'))
      true
    else
      false
    end
  end

  def did_session_update(sess_id)
    current_sess_updated_at = sessions.find_by(session_id: sess_id, program_id: id).updated_at.strftime('%c') if updated_at
    if (import_time != nil) && (current_sess_updated_at == import_time.strftime('%c'))
      true
    else
      false
    end
  end

  def build_schedule
    sessions_clean = delete_if_name_is_nil
    speakers_clean = delete_if_name_is_nil_speaker
    
    @schedule = "<table class=\"schedule\">"

    sessions_clean.sort_by! {|session| [session["start_time"], session["name"]]}.each do |session|
      day_title = "<h2 class=\"titleDate\"><strong>#{format_date(session["start_time"])}</strong></h2>"
      start_time = format_time(session["start_time"])
      end_time = format_time(session["end_time"])
      weekday = format_day(session["start_time"])
      conf_code = split_conf_code(session["session_tracks"])
      speakers = split_speakers(session["speaker_id"])
      description = session["description"]
      filters = session["filters"].split(",")
      short_description = "#{get_plain_text(description).split(' ')[0..50].join(' ')}...".gsub("&nbsp;", "")
      link = if session["link_urls"].empty? || session["link_urls"].nil?
                "#"
            else
              session["link_urls"]
            end
      
      meeting_type = ""
      filter_list = ""
      filters.each do |filter| 
        filter_no_char = filter.gsub(/\W/, "")
        meeting_type << "<div class=\"#{filter_no_char} filter\">#{filter}</div>"
        filter_list << filter_no_char
      end
      
      circles = ""

      conf_code.split(";").each do |code| 
        circles << "<div title=\"#{code}\" class=\"#{format_conf_code(code)} circle\"></div>"
      end

      @schedule << "<tr><td colspan=2 class=\"day\" id=\"#{weekday}\">
                  #{day_title}</td></tr>" unless @schedule.include?(day_title)
      
      @schedule << <<-HERE
                      <tr>
                        <td class="#{filter_list} #{format_conf_code(conf_code)} dateTime">#{start_time} &ndash; #{end_time}</td>
                        <td class="#{filter_list} #{format_conf_code(conf_code)} sessionInfo">
                          <p class="sessionName"><strong>#{session["name"]}</strong></p>
                          <p class="speakers"><em>#{speakers}</em></p>
                          <div class="shortDescription" style="display: none;"> #{short_description} </div>
                          <div class="longDescription" style="display: none;">#{description}</div>
                          <p style="display: none;"><span class="readMore" id="#{session["session_id"]}">Read More</span></p>
                          <p><a href="#{link}">Click here for more information</a></p>
                          #{meeting_type}
                          #{circles}
                        </td>
                      </tr>
                    HERE
    
    end

    @schedule << "</table>"
    
    speakers_clean.each do |speaker| 
      spid = speaker["speaker_id"]
      @schedule.gsub!(spid, 
                      "#{speaker["fname"].strip} #{speaker["lname"].strip}, 
                      #{speaker["title"].strip}, #{speaker["company"].strip}") if @schedule.include?(spid)
    end

    fix_cp1252_utf8(@schedule)

  end


  def format_date(date_string)
    DateTime.parse(date_string.to_s).utc.strftime("%A, %B %e, %Y")
  end

  def format_day(day_string)
    DateTime.parse(day_string.to_s).utc.strftime("%A")
  end

  def format_time(time_string)
    DateTime.parse(time_string.to_s).utc.strftime("%l:%M %p")
  end

  def self.format_date_time_est(string)
    Time.zone = 'Eastern Time (US & Canada)'
    DateTime.parse(string.to_s).in_time_zone.strftime("%A, %B %e, %Y at %l:%M %p EST")
  end

  def split_conf_code(session_tracks)
    #edge case: track itself contains a comma which needs to be preserved. this method seperates tracks by semicolon, and subs back in the literal comma (grammatically often followed by a space)
    session_tracks.gsub(",",";").gsub("; ", ", ")
  end

  def format_conf_code(session_tracks)
    #replaces any literal commas (grammatically followed by a whitespace char), and whitespace chars with no spaces THEN replaces semicolon seperator with space. Spacing important for CSS classes. 
    session_tracks.gsub(/(,\s|\s)/, "").gsub(/;/, " ")
  end

  def split_speakers(presenter)
    presenter.split(',').join('<br />')
  end

  def get_plain_text(text)
    text.gsub(/<.*>/,"").gsub(/<\/.*>/, "")
  end

  def fix_cp1252_utf8(text)
  text.encode('cp1252',
              :fallback => {
                "\u06EA" => "\x6ea".force_encoding("cp1252"),
                "\u06DD" => "\x6dd".force_encoding("cp1252"),
                "\uFFFD" => "\xfffd".force_encoding("cp1252"),
                "\u0081" => "\x81".force_encoding("cp1252"),
                "\u008D" => "\x8D".force_encoding("cp1252"),
                "\u008F" => "\x8F".force_encoding("cp1252"),
                "\u0090" => "\x90".force_encoding("cp1252"),
                "\u009D" => "\x9D".force_encoding("cp1252")
              })
      .force_encoding("utf-8").encode("utf-8")
  end



end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :download, :edit, :update, :destroy, :text]
  
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @created_at_time = Program.format_date_time_est(@program.created_at)
    @updated_at_time = Program.format_date_time_est(@program.updated_at)
  end

  def text
    @html_page = @program.build_schedule
  end

  def download
    respond_to do |format|
      format.html { send_data @program.build_schedule, filename: "#{@program.name}-#{Date.today}.html" }
    end
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    
      file_session = params[:file_session]
      file_speaker = params[:file_speaker]
      @program = Program.create!(program_params)
      @program.user_id = current_user.id
      @program.import_time = 0
      @program.save
      sessions_count = Session.import(file_session, @program.id)
      speakers_count = Speaker.import(file_speaker, @program.id)
    if sessions_count > 0 && speakers_count > 0
      respond_to do |format|
        format.html { redirect_to @program, notice: "Program was successfully created with #{sessions_count} sessions and #{speakers_count} speakers." }
        format.json { render :show, status: :created, location: @program }
      end
    else
      redirect_to new_program_path, alert: "Unexpected CSV format, no rows were imported. Please download template."
      @program.destroy!
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
      file_session = params[:file_session]
      file_speaker = params[:file_speaker]
      sessions_count = Session.import(file_session, @program.id)
      speakers_count = Speaker.import(file_speaker, @program.id)
      @program.import_time = Time.now
      @program.save
      if sessions_count > 0 && speakers_count > 0
        respond_to do |format|
          if @program.update(program_params)
            format.html { redirect_to @program, notice: 'Program was successfully updated.' }
            format.json { render :show, status: :ok, location: @program }
          else
            format.html { render :edit }
            format.json { render json: @program.errors, status: :unprocessable_entity }
          end
        end
    else
      redirect_to edit_program_path, alert: "Unexpected CSV format, no rows were imported. Please download template."
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.permit(:name, :created_at)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
  
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= label_tag(:name, "Program name") %> 
    <%= text_field_tag :name, @program.name || "", class: 'form-control' %>
  </div>
  <br />
  <div class="field">
    <%= label_tag(:file_session, "Session CSV") %> <%= file_field_tag :file_session, accept: 'text/csv' %>
  </div>
  <br />  
  <div class="field">
    <%= label_tag(:file_speaker, "Speaker CSV") %> <%= file_field_tag :file_speaker, accept: 'text/csv' %>
  </div>
  <br />
  <div class="actions">
    <%= submit_tag "Submit Program", class: "btn btn-primary" %>
  </div>
  </div>

app/views/programs/edit.html.erb
  <% if @program.user_id != current_user.id %>
  <h1>Whoops! This program does not belong to you.</h1>
<% else %>
  <h1>Edit Program</h1>
    <%= form_tag(@program, multipart: true, method: "patch") do %>
      <%= render 'form' %>
    <% end %>
    <%= link_to 'Show', @program %> |
    <%= link_to 'Back', programs_path %>
<% end %>

app/views/programs/index.html.erb
  <h1>Your Programs</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Created at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @programs.each do |program| %>
      <% if program.user_id == current_user.id %>
        <tr>
          <td><%= program.name %></td>
          <td><%= program.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%A, %D, %r") %> EST </td>
          <td><%= link_to 'View', program %></td>
          <td><%= link_to 'Edit', edit_program_path(program) %></td>
          <td><%= link_to 'Delete', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Program', new_program_path, class: "btn btn-primary" %>

app/views/programs/new.html.erb
<h1>New Program</h1>
<%= form_tag(@program, multipart: true) do %>
  <%= render 'form' %>
<% end %>
<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<%= link_to 'Back', programs_path, class: 'btn btn-default btn-sm', role: "button" %>
<% if @program.user_id != current_user.id %>
  <h1>Whoops! This program does not belong to you.</h1>
<% else %>
<div class="page-header">
  <h1><%= @program.name %></h1>
</div>
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title"><%= @program.name %> Info</h3></div>
  <div class="panel-body">
    <p>
      <strong>Created at:</strong>
      <%= @created_at_time %><br />
       <strong>Last updated:</strong>
      <%= @updated_at_time %>
    </p>

    <p>
      <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <%= link_to 'Download HTML File', program_download_path, class: "btn btn-default", role: "button" %> 
        <%= link_to 'Show HTML', program_text_path, class: "btn btn-default", role: "button" %>
      </div>
    </p>
  </div>
</div>
<div class="page-header">
  <h1>Sessions for <%= @program.name %> &nbsp; &nbsp; <small><%= link_to 'Upload New Sessions', edit_program_path(@program), class: 'btn btn-success btn-sm' %></small></h1>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Key</th>
    </tr>
  </thead>
  <tbody>
    <tr class="danger">
      <td>Session has been deleted.</td>
    </tr>
    <tr class="info">
      <td>Session has been updated since last import. Update information on linked page.</td>
    </tr>
    <tr class="warning">
      <td>Session does not have a detail page linked.</td>
    </tr>
     <tr>
      <td>Session has not been updated, deleted, and has a detail page in place.</td>
    </tr>

  </tbody>
</table>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download HTML</th>
      <th>Show HTML</th>
      <th>Link</th>
    </tr>
  </thead>

  <tbody>
    <% @program.sessions.sort_by { |session| [session.link_urls, session.start_time, session.name] }. each do |session| %>
    <% if session.deleted == true %>
       <tr class="danger">
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td><%= link_to "DELETED", session.link_urls %></td> 
      </tr>
      <% elsif session.link_urls === "#" || session.link_urls.nil? || session.link_urls.empty? %>
      <tr class="warning">
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td>None</td> 
      </tr>
    <% elsif ( @program.did_speakers_update(session.session_id) && @program.did_session_update(session.session_id) ) %>
      <tr class="info">
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td><%= link_to 'Speaker & Session Updated', session.link_urls %></td>
      </tr>
  <% elsif @program.did_speakers_update(session.session_id) %>
      <tr class="info">
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td><%= link_to 'Speaker Updated', session.link_urls %></td>
      </tr>
  <% elsif @program.did_session_update(session.session_id) %>
      <tr class="info">
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td><%= link_to 'Session Updated', session.link_urls %></td>
      </tr>
    

    <% else %>
        <tr>
        <td><%= session.name %></td>
        <td><%= link_to 'Download', program_session_download_path(session.program_id, session.id) %></td>
        <td><%= link_to 'View', program_session_path(session.program_id, session.id) %>
        </td>
        <td><%= link_to "Link", session.link_urls %></td> 
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/programs/text.html.erb
<% if @program.user_id != current_user.id %>
  <h1>Whoops! This program does not belong to you.</h1>
<% else %>
  <h1>Conference Program HTML for <%=@program.name %></h1>
  <p>Use this to copy and paste into your webpage. If you are using a CMS, you will most likely have an "HTML" button on the text editor. </p>
  <%= link_to 'Back', program_path, class: "btn btn-default btn-sm" %>
  <br />
  <br />
  <%= text_area_tag 'html', @html_page, size: "100x70" %>
  <br />
<% end %>